# Generated by Django 3.2 on 2021-04-29 13:20

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210429_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
