# Generated by Django 3.2 on 2021-04-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_default_phone_number'),
        ('profiles', '0006_alter_userprofile_default_phone_number'),
    ]

    operations = [
    ]
