# Generated by Django 3.2 on 2021-04-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_photos_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
