# Generated by Django 3.2 on 2021-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photosadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
