# Generated by Django 3.2 on 2021-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(max_length=4),
        ),
    ]
