# Generated by Django 3.2 on 2021-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
