# Generated by Django 3.2 on 2021-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
