# Generated by Django 3.2 on 2021-04-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_phone_number'),
        ('checkout', '0014_alter_order_phone_number'),
    ]

    operations = [
    ]
