# Generated by Django 3.2 on 2021-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photos_ne'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
