# Generated by Django 3.2 on 2021-04-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_photosadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
